org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.248
neo_version_range=[21,)
loader_version_range=[4,)

mod_id=millenaire_ftb_chunks_compat
mod_name=Millenaire FTB Chunks Compat
mod_license=LGPL-3.0-only
mod_version=0.2
mod_group_id=dev.vt
mod_authors=VeiTr
mod_description=Mod for Millenaire and FTB Chunks compatibility

## Dependency Versions
ftb_chunks_version=2101.1.21
ftb_library_version=2101.1.35
architectury_version=13.0.11

ftb_chunks_project_id=314906
ftb_chunks_file_id=8520252

ftb_library_project_id=404465
ftb_library_file_id=8569579

architectury_project_id=419699
architectury_file_id=8492726

ftb_teams_project_id=404468
ftb_teams_file_id=7878281

millenaire_project_id=270871
millenaire_file_id=8508130

## Publishing IDs
curseforge_project_id=1648477
modrinth_project_id=HUAcBFOa
